;PRACTICA 2: MULTIPLICADOR POR 5
;OCTUBRE 10
;LARISSA REGINA SALAZAR MONTES
;MARCOS AARON RODRIGUEZ BERNAL

		LIST P=16F887		;DIRECTIVA INDICA EL PIC QUE SE VA A USAR 
		INCLUDE "P16F887.INC";DIRECTIVA PARA CARGAR LA LIBRERIA DEL PIC
		ORG 0X00			;DIRECTIVA QUE INDICA QUE LA PRIMERA INSTRUCCION SE CARGA EN LA DIR 0X00

		GOTO INICIO			;NOS MANDA A LA ETIQUETA INICIO

INICIO	BSF 	STATUS, RP0	;PONE EN 1 EL BIT RP0 DEL STATUS
		BSF 	STATUS, RP1	;PONE EN 1 EL BIT RP1 DEL STATUS, ESTO NOS MANDO AL BANCO 3
		CLRF 	ANSEL		;LIMPIA EL REGISTRO ANSEL, ES DECIR, LO PONE EN CEROS. SE CONFIGURA EL PORTA COMO ENTRADA DIGITAL.
		CLRF 	ANSELH		;LIMPIA EL REGISTRO ANSELH, ES DECIR, SE CONFIGURA LOS PINES DEL PORTB COMO I/O DIGITAL.
		CLRF 	TRISB		;LIMPIA EL REGISTRO TRISB, ES DECIR, SE ASIGNA EL PUERTO B COMO SALIDA.
		BCF 	STATUS, RP0	;PONE EN 0 EL BIT RP0 DEL STATUS
		BCF 	STATUS, RP1

CICLO	MOVF	PORTA,W	;REALIZA EL CICLO DE SUMA DEL PUERTA A W
		ADDWF	PORTA,W
		ADDWF	PORTA,W
		ADDWF	PORTA,W
		ADDWF	PORTA,W

		MOVWF	PORTB	;MUEVE EL RESULTADO DE W A PORTB
		GOTO	CICLO
		END