;Esto es un comentario
;Enunciado de la practica 1
;Fecha
;Integrantes del equipo

		LIST	P=16F887		;INDICA EL PIC A USAR
		INCLUDE "p16F887.INC"	;CARGA LA LIBRERIA DEL PIC		
		ORG		0X00			;INDICA EL ORIGEN DEL PROGRAMA
;ESPACIO PARA DECLARAR REGISTROS;EJEMPLO: DATA EQU	0X20
		GOTO	INICIO			; IR A LA ETIQUETA DE INICIO

INICIO	BSF 	STATUS,  RP0	;PONE RP0 EN 1
		BSF 	STATUS,	 RP1	;PONE RP1 EN 1
		CLRF	TRISB			;PONEMOS EN 0 A TRISB, PONE PORTB COMO OUT
		CLRF	ANSEL			;PONE EN CEROS A ANSEL, LOS PINES DEL A Y E SON I/O DIGITAL
		CLRF	ANSELH			;PONEMOS EN CEROS A ANSELH, LOS PINES DEL PORTB SON I/O DIGITAL
		BCF		STATUS,	 RP0	;PONE RP0 EN 0
		BCF		STATUS,	 RP1	; PONE RP1 EN 0
	
REPETIR	MOVF	PORTA,	 W		;MUEVE EL CONTENIDO DEL PORTA AL REGISTRO W
		MOVWF	PORTB			;MUEVE EL CONTENIDO DE W AL PORTB
		GOTO	REPETIR	
		END