;Practica 3: Multiplicador por n
;Octubre 3 del 2022
;Larissa Regina Salazar Montes
;Marcos Aaron Rodriguez Bernal

		LIST	P=16F887		;INDICA EL PIC A USAR
		INCLUDE "p16F887.INC"	;CARGA LA LIBRERIA DEL PIC		

		ORG		0X00			;INDICA EL ORIGEN DEL PROGRAMA
;ESPACIO PARA DECLARAR REGISTROS;EJEMPLO: DATA EQU	0X20
		MULTI	EQU	.3	;MULTIPLICADOR 	
		M		EQU	0X20		
		GOTO	INICIO		; IR A LA ETIQUETA DE INICIO	
		
INICIO	
		BSF 	STATUS,  RP0	;PONE RP0 EN 1
		BSF 	STATUS,	 RP1	;PONE RP1 EN 1
		CLRF	TRISB			;PONEMOS EN 0 A TRISB, PONE PORTB COMO OUT
 		CLRF	ANSEL			;PONE EN CEROS A ANSEL, LOS PINES DEL A Y E SON I/O DIGITAL
		CLRF	ANSELH			;PONEMOS EN CEROS A ANSELH, LOS PINES DEL PORTB SON I/O DIGITAL
		BCF		STATUS,	 RP0	;PONE RP0 EN 0
		BCF		STATUS,	 RP1	;PONE RP1 EN 0
	;	MOVLW	MULTI
	;	MOVWF	M
	;	MOVLW	0X00
MULTIPLICAR	
		ADDWF	PORTA,	W	;MUEVE EL VALOR DEL ENTRADA A W	
		DECFSZ	MULTI,	1		
		GOTO	MULTIPLICAR
		MOVWF	PORTB
		GOTO	INICIO
		END